# Generated by Django 5.0.1 on 2024-01-11 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clothingCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryID', models.IntegerField()),
                ('clothingType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='clothingStyles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('styleID', models.IntegerField()),
                ('styleType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='todolist',
        ),
        migrations.CreateModel(
            name='userClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothingID', models.IntegerField()),
                ('brand', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clothingcategories')),
                ('styleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clothingstyles')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
