# Generated by Django 5.0.1 on 2024-01-12 00:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_item_remove_userclothes_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclothes',
            name='clothingID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
