# Generated by Django 5.0.1 on 2024-01-12 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userclothes_clothingid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userclothes',
            name='clothingID',
        ),
    ]
