# Generated by Django 5.0.1 on 2024-01-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_userclothes_clothingid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclothes',
            name='name',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
