# Generated by Django 5.0.1 on 2024-04-29 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_shoesize_size_alter_item_category_item_shoesize_and_more'),
        ('item', '0004_item_size_alter_item_category'),
    ]

    operations = [
    ]
