# Generated by Django 4.2.9 on 2024-04-24 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_shoesize'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shoeSize',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item.shoesize'),
        ),
        migrations.AddField(
            model_name='shoesize',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shoe_sizes', to='item.category'),
        ),
        migrations.AddField(
            model_name='size',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='item.category'),
        ),
    ]
