# Generated by Django 4.2.9 on 2024-04-24 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_item_shoesize_shoesize_category_size_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoesize',
            name='category',
        ),
        migrations.RemoveField(
            model_name='size',
            name='category',
        ),
    ]
