# Generated by Django 5.0.1 on 2024-03-25 00:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='clothingCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='clothingStyles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Closet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25)),
                ('is_public', models.BooleanField(default=True, verbose_name='Public')),
                ('closetUser', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(blank=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='post_photos')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25, verbose_name='*Name')),
                ('image', models.ImageField(default='', upload_to='clothing_photos')),
                ('bloguser', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.clothingcategories', verbose_name='*Category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.colors', verbose_name='*Color')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.clothingstyles', verbose_name='*Style')),
            ],
        ),
        migrations.CreateModel(
            name='postClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('clothing_item', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.userclothes')),
            ],
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('accessory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Accessory', to='blog.userclothes')),
                ('bottoms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bottoms', to='blog.userclothes')),
                ('footwear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Footwear', to='blog.userclothes')),
                ('outerwear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Outerwear', to='blog.userclothes')),
                ('top', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Top', to='blog.userclothes')),
            ],
        ),
        migrations.CreateModel(
            name='closetClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closet', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.closet')),
                ('user', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('clothing_item', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.userclothes')),
            ],
        ),
    ]
