# Generated by Django 5.0.1 on 2024-01-22 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clothingCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryID', models.IntegerField()),
                ('clothingType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='clothingStyles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('styleID', models.IntegerField()),
                ('styleType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='userClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=100)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.clothingcategories')),
                ('styleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.clothingstyles')),
            ],
        ),
    ]
