# Generated by Django 5.0.1 on 2024-01-24 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_clothingcategories_clothingstyles_userclothes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userclothes',
            name='bloguser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userclothes',
            name='name',
            field=models.CharField(default='unknown_item', max_length=100),
        ),
    ]
