# Generated by Django 5.0.1 on 2024-04-12 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_when',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_message_when', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CommentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_when', models.DateTimeField(auto_now_add=True)),
                ('modified_when', models.DateTimeField(auto_now=True)),
                ('commentmembers', models.ManyToManyField(related_name='commentsection', to=settings.AUTH_USER_MODEL)),
                ('commentuser', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commentUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified_when',),
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='commentions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commentMessage', to='blog.commentsection'),
        ),
    ]
