# Generated by Django 5.0.1 on 2024-01-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_userclothes_bloguser_alter_userclothes_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userclothes',
            old_name='categoryID',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='userclothes',
            old_name='styleID',
            new_name='style',
        ),
        migrations.AlterField(
            model_name='userclothes',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
