# Generated by Django 5.0.1 on 2024-04-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='convo',
            name='last_message',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
