# Generated by Django 5.0.1 on 2024-01-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_categoryid_userclothes_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclothes',
            name='color',
            field=models.CharField(default='black', max_length=50),
        ),
    ]
