# Generated by Django 5.0.1 on 2024-01-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_userclothes_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothingcategories',
            old_name='clothingType',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='clothingstyles',
            old_name='styleType',
            new_name='style',
        ),
        migrations.RemoveField(
            model_name='clothingcategories',
            name='categoryID',
        ),
        migrations.RemoveField(
            model_name='clothingstyles',
            name='styleID',
        ),
        migrations.AlterField(
            model_name='userclothes',
            name='color',
            field=models.CharField(default='', max_length=50),
        ),
    ]
