# Generated by Django 5.0.1 on 2024-01-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_colors_alter_userclothes_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclothes',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='clothing_photos'),
        ),
    ]
