# Generated by Django 5.0.1 on 2024-02-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_userclothes_name_closet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclothes',
            name='name',
            field=models.CharField(default='', max_length=25, unique=True),
        ),
    ]
