# Generated by Django 5.0.1 on 2024-02-09 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_userclothes_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclothes',
            name='closet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.closet'),
        ),
        migrations.AlterField(
            model_name='userclothes',
            name='name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
