# Generated by Django 5.0.1 on 2024-03-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_userclothes_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclothes',
            name='name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
