# Generated by Django 5.0.1 on 2024-03-22 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_userclothes_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclothes',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.clothingcategories', verbose_name='*Category'),
        ),
        migrations.AlterField(
            model_name='userclothes',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.colors', verbose_name='*Color'),
        ),
        migrations.AlterField(
            model_name='userclothes',
            name='image',
            field=models.ImageField(default='', upload_to='clothing_photos'),
        ),
        migrations.AlterField(
            model_name='userclothes',
            name='name',
            field=models.CharField(default='', max_length=25, verbose_name='*Name'),
        ),
        migrations.AlterField(
            model_name='userclothes',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.clothingstyles', verbose_name='*Style'),
        ),
        migrations.CreateModel(
            name='closetClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closet', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.closet')),
                ('clothing_item', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.userclothes')),
                ('user', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='postClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing_item', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.userclothes')),
                ('user', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
