# Generated by Django 5.0.1 on 2024-02-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_userclothes_closet_alter_userclothes_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclothes',
            name='closet',
            field=models.IntegerField(default=-1),
        ),
    ]
