# Generated by Django 5.0.1 on 2024-02-15 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_userclothes_closet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclothes',
            name='closet',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.closet'),
        ),
    ]
