# Generated by Django 5.0.1 on 2024-03-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_userclothes_category_alter_userclothes_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='closet',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
