# Generated by Django 5.0.1 on 2024-03-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_userclothes_closet_alter_userclothes_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='clothing_photos'),
        ),
        migrations.AlterField(
            model_name='userclothes',
            name='image',
            field=models.ImageField(default='', upload_to='clothing_photos'),
        ),
    ]
