# Generated by Django 5.0.1 on 2024-03-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_closetoutfits'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='name',
            field=models.CharField(default='', max_length=25, verbose_name='Name'),
        ),
    ]
