# Generated by Django 5.0.2 on 2024-04-16 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_image_alter_post_content_alter_post_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userclothes',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.clothingcategories', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='userclothes',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.colors', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='userclothes',
            name='name',
            field=models.CharField(default='', max_length=25, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='userclothes',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.clothingstyles', verbose_name='Style'),
        ),
    ]
