# Generated by Django 5.0.1 on 2024-04-29 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_title_comment_likes'),
        ('blog', '0018_post_image_alter_post_content_alter_post_title'),
    ]

    operations = [
    ]
