# Generated by Django 5.0.1 on 2024-04-29 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_merge_20240429_0510'),
        ('blog', '0019_merge_20240429_0516'),
    ]

    operations = [
    ]
