# Generated by Django 5.0.1 on 2024-03-25 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_image_alter_post_content_alter_post_title'),
        ('blog', '0024_postclothes'),
    ]

    operations = [
    ]
