# Generated by Django 5.0.1 on 2024-03-22 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_userclothes_category_alter_userclothes_color_and_more'),
        ('blog', '0024_postclothes'),
    ]

    operations = [
    ]
