# Generated by Django 5.0.1 on 2024-03-18 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_postclothes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
