# Generated by Django 5.0.1 on 2024-03-22 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_merge_20240322_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
